apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-exercicio-nginx
  
spec:
  selector:
    matchLabels:
      app: k8s-exercicio-nginx
  replicas: 3
  template:
    metadata: 
      labels: 
        app: k8s-exercicio-nginx
  
    spec:
      containers:
      - name: nginx
        image: nginx:1.17-alpine
        #image: biliano/k8s-exercicio-nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-conf
          readOnly: true
        - mountPath: /usr/share/nginx/html
          name: nginx-index-html
          readOnly: true
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "200Mi"
            cpu: "250m"
      
      volumes: 
      - name: nginx-conf
        configMap: 
          name: k8s-exercicio-nginx-configmap
          items: 
            - key: nginx.conf
              path: nginx.conf
      - name: nginx-index-html
        configMap: 
          name: k8s-exercicio-nginx-configmap
          items: 
            - key: index.html
              path: index.html
